AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - config/**/*
    - lib/tasks/*
    - Gemfile
    - features/**/*
    - spec/**/*

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

LineLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

FormatString:
  EnforcedStyle: percent

NumericLiterals:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

DotPosition:
  EnforcedStyle: trailing

Style/SymbolArray:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Style/Lambda:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Style/GuardClause:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Layout/IndentationConsistency:
  EnforcedStyle: rails
