language: ruby
rvm: 2.5.1
services: postgresql
bundler_args: "--without develop --deployment -j4"
cache: bundler
before_install:
  - gem install rubocop
before_script:
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:setup
script:
  - bundle exec rake test
  - rubocop --fail-level=W
